export const metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial -chandrashekar",
    template:"%s | Chanu"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <body>
      {/* <header style={{backgroundColor:"blue"}}>
       <p> Header</p>
      </header> */}
        {children}
        {/* <footer style={{backgroundColor:'yellow'}}>
       <p> Footer</p>
      </footer> */}
      </body>
      
    </html>
  )
}
